Repository mountain-sailors/stock-battle-server, pull requests merged in 2021-11, with the labels that each got.

#35 [FEAT] Game Scheduler
  src/@types/WinConditionType.ts
  src/game/calculator.ts
  src/game/endGame.ts
  src/game/startGame.ts
  src/jobs/gameScheduler.ts
  src/jobs/index.ts
  src/models/UserGameHistory.ts
  src/models/UserStock.ts
  src/utils/stocks.ts
  swagger/swagger.yaml
Labels: feature✨

#36 [FEAT] Dashboard API
  package-lock.json
  src/controllers/dashboardController.ts
  src/game/calculator.ts
  src/game/endGame.ts
  src/game/gameData.ts
  src/game/startGame.ts
  src/jobs/stockScheduler.ts
  src/models/Stock.ts
  src/routes/roomRouter.ts
  src/services/dashboardService.ts
  src/services/roomService.ts
  src/services/userStockService.ts
  src/sockets/.gitkeep
  src/utils/stocks.ts
  swagger/swagger.yaml
Labels: feature✨

#38 [TEST] Jest setting #29
  .eslintrc.json
  jest.config.js
  nodemon.json
  package-lock.json
  package.json
  src/app.ts
  src/server.ts
  src/tests/any.test.ts
Labels: chore🧺, test✍️

#39 [FEAT] Winston Setting
  logs/.2175ca2113711a4fb9c5cf33852ebfa9969e83f3-audit.json
  logs/.ba81331cb9d70de713aa7edad0bae69ac43bb076-audit.json
  logs/2021-11-09.log
  logs/2021-11-09_error.log
  package-lock.json
  package.json
  src/config/logger.ts
  src/models/index.ts
  src/server.ts
Labels: feature✨

#44 [FIX] room response upon gameStatus #22 #43
  src/services/roomService.ts
  src/services/userGameHistoryService.ts
Labels: bug🐞

#45 [TEST] Room API tests and error handling #37
  package-lock.json
  src/@types/statusCode.ts
  src/controllers/roomController.ts
  src/services/roomService.ts
  src/utils/generateInvitationCode.ts
  tests/room.test.ts
Labels: refactor🛠, test✍️

#46 [TEST] User API tests, error handling and bcrypt
  package-lock.json
  package.json
  src/auth/passport.ts
  src/controllers/userController.ts
  src/models/User.ts
  src/routes/userRouter.ts
  src/services/userService.ts
  tests/user.test.ts
Labels: bug🐞, feature✨, test✍️

#47 [TEST] Test code for user stock API & Error handling #42
  src/controllers/userStockController.ts
  src/services/userStockService.ts
  tests/userStock.test.ts
Labels: test✍️

#49 [TEST] UserGameHistory API test
  src/controllers/userGameHistoryController.ts
  tests/userGameHistory.test.ts
Labels: test✍️

#51 [TEST] Tests for stock API
  src/app.ts
  src/controllers/stockController.ts
  src/jobs/stockScheduler.ts
  tests/stock.test.ts
Labels: test✍️

#53 [FEAT] Players Info API and fix some bugs
  src/controllers/dashboardController.ts
  src/controllers/playerController.ts
  src/game/gameData.ts
  src/routes/index.ts
  src/routes/playerRouter.ts
  src/services/playerService.ts
  src/services/roomService.ts
  swagger/swagger.yaml
Labels: bug🐞, feature✨

#57 [FEAT] Game Result API
  src/controllers/userGameHistoryController.ts
  src/routes/userGameHistoryRouter.ts
  src/services/userGameHistoryService.ts
  swagger/swagger.yaml
Labels: feature✨

#58 [FIX] Add color to playerInfo API response & add more stock data
  src/services/playerService.ts
  src/utils/stocks.ts
Labels: fix

#55 [FEAT] Add yml files for AWS ci/cd
  appspec.yml
  buildspec.yml
  initialize.sh
  start.sh
Labels: ci/cd

#63 [FIX] SSE improvement #62
  src/services/dashboardService.ts
Labels: fix

#65 [FIX] Stock amount type and cancelRoom
  src/game/startGame.ts
  src/models/UserStock.ts
Labels: bug🐞

#66 [REFACTOR] SSE initial data
  src/controllers/dashboardController.ts
  src/game/calculator.ts
  src/game/endGame.ts
  src/game/gameData.ts
  src/services/dashboardService.ts
  src/services/roomService.ts
Labels: refactor🛠
