Repository mountain-sailors/stock-battle-server, pull requests merged in 2022-01, with the labels that each got.

#70 [FEAT] room 한 개에 대한 정보 제공 API
  src/controllers/roomController.ts
  src/routes/roomRouter.ts
  swagger/swagger.yaml
Labels: feature✨

#69 [FIX] Email verification & update password
  package-lock.json
  package.json
  src/controllers/userController.ts
  src/models/User.ts
  src/routes/userRouter.ts
  src/services/roomService.ts
  src/services/userService.ts
  src/utils/generateInvitationCode.ts
  src/utils/generateVerificationCode.ts
  swagger/swagger.yaml
Labels: fix

#72 [hotfix] Fix CI/CD
  initialize.sh
  start.sh
Labels: bug🐞, ci/cd

#73 [hotfix] cicd permission
  appspec.yml
  buildspec.yml
  start.sh
Labels: bug🐞, ci/cd

#75 [FEAT] Username validation
  initialize.sh
  src/controllers/userController.ts
  src/routes/userRouter.ts
  src/services/userService.ts
  start.sh
  swagger/swagger.yaml
Labels: feature✨, ci/cd
